CREATE OR REPLACE TABLE `ZanreHry` (
	`ID_hra` INTEGER NOT NULL,
	`ID_zaner` INTEGER NOT NULL,
	PRIMARY KEY(`ID_hra`, `ID_zaner`)
);

CREATE OR REPLACE TABLE `Zaner` (
	`ID_zaner` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`Zaner` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`ID_zaner`)
);

CREATE OR REPLACE TABLE `Komentare` (
	`ID_komentar` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`ID_pouzivatel` INTEGER NOT NULL,
	`ID_hra` INTEGER NOT NULL,
	`Popis` TEXT(65535) NOT NULL,
	`Datum_pridania` DATETIME NOT NULL,
	PRIMARY KEY(`ID_komentar`)
);

CREATE OR REPLACE TABLE `Hry` (
	`ID_hra` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`ID_nahravac` INTEGER NOT NULL,
	`Nazov` VARCHAR(255) NOT NULL,
	`Autor` VARCHAR(255),
    `Like` INTEGER UNSIGNED DEFAULT 0,
    `Hodnotenie` INTEGER UNSIGNED DEFAULT 0,
	`Popis` TEXT(65535),
	`Obrazok` VARCHAR(255) NOT NULL,
	`Datum_pridania` DATETIME NOT NULL,
	`Link` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`ID_hra`)
);

CREATE OR REPLACE TABLE `Pouzivatelia` (
	`ID_pouzivatel` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`Prezivka` VARCHAR(50) NOT NULL,
	`Email` VARCHAR(255) NOT NULL UNIQUE,
	`Heslo` VARCHAR(255) NOT NULL,
	`Obrazok` VARCHAR(255) DEFAULT 'default.png',
	PRIMARY KEY(`ID_pouzivatel`)
);

CREATE OR REPLACE TABLE `Admini` (
    `ID_admin` INTEGER NOT NULL,
    PRIMARY KEY(`ID_admin`)
);

ALTER TABLE `Komentare`
ADD FOREIGN KEY(`ID_pouzivatel`) REFERENCES `Pouzivatelia`(`ID_pouzivatel`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Hry`
ADD FOREIGN KEY(`ID_nahravac`) REFERENCES `Pouzivatelia`(`ID_pouzivatel`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Komentare`
ADD FOREIGN KEY(`ID_hra`) REFERENCES `Hry`(`ID_hra`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `ZanreHry`
ADD FOREIGN KEY(`ID_hra`) REFERENCES `Hry`(`ID_hra`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `ZanreHry`
ADD FOREIGN KEY(`ID_zaner`) REFERENCES `Zaner`(`ID_zaner`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Admini`
ADD FOREIGN KEY(`ID_admin`) REFERENCES `Pouzivatelia`(`ID_pouzivatel`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
